spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.245.131/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  application:
    name: order

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
env:
  dev3
girl:
  name:lala
  age:18
